/**
 * Bible book mappings - maps various names and abbreviations to Logos ref codes
 */
export const BIBLE_BOOKS: Record<string, string> = {
    // Old Testament
    'genesis': 'Ge', 'gen': 'Ge', 'ge': 'Ge',
    'exodus': 'Ex', 'exod': 'Ex', 'ex': 'Ex',
    'leviticus': 'Lv', 'lev': 'Lv', 'lv': 'Lv',
    'numbers': 'Nu', 'num': 'Nu', 'nu': 'Nu', 'nm': 'Nu',
    'deuteronomy': 'Dt', 'deut': 'Dt', 'dt': 'Dt', 'de': 'Dt',
    'joshua': 'Jos', 'josh': 'Jos', 'jos': 'Jos',
    'judges': 'Jdg', 'judg': 'Jdg', 'jdg': 'Jdg', 'jg': 'Jdg',
    'ruth': 'Ru', 'ru': 'Ru', 'rth': 'Ru',
    '1samuel': '1Sa', '1sam': '1Sa', '1sa': '1Sa', '1sm': '1Sa', 'isamuel': '1Sa', 'isam': '1Sa',
    '2samuel': '2Sa', '2sam': '2Sa', '2sa': '2Sa', '2sm': '2Sa', 'iisamuel': '2Sa', 'iisam': '2Sa',
    '1kings': '1Ki', '1kgs': '1Ki', '1ki': '1Ki', '1kg': '1Ki', 'ikings': '1Ki', 'ikgs': '1Ki',
    '2kings': '2Ki', '2kgs': '2Ki', '2ki': '2Ki', '2kg': '2Ki', 'iikings': '2Ki', 'iikgs': '2Ki',
    '1chronicles': '1Ch', '1chr': '1Ch', '1ch': '1Ch', 'ichronicles': '1Ch', 'ichr': '1Ch',
    '2chronicles': '2Ch', '2chr': '2Ch', '2ch': '2Ch', 'iichronicles': '2Ch', 'iichr': '2Ch',
    'ezra': 'Ezr', 'ezr': 'Ezr',
    'nehemiah': 'Ne', 'neh': 'Ne', 'ne': 'Ne',
    'esther': 'Es', 'esth': 'Es', 'es': 'Es', 'est': 'Es',
    'job': 'Job', 'jb': 'Job',
    'psalms': 'Ps', 'psalm': 'Ps', 'ps': 'Ps', 'psa': 'Ps', 'pss': 'Ps',
    'proverbs': 'Pr', 'prov': 'Pr', 'pr': 'Pr', 'prv': 'Pr',
    'ecclesiastes': 'Ec', 'eccl': 'Ec', 'ecc': 'Ec', 'ec': 'Ec', 'eccles': 'Ec', 'qoh': 'Ec',
    'songofsolomon': 'So', 'songofsongs': 'So', 'song': 'So', 'sos': 'So', 'so': 'So', 'ss': 'So', 'canticles': 'So', 'cant': 'So',
    'isaiah': 'Is', 'isa': 'Is',
    'jeremiah': 'Je', 'jer': 'Je', 'je': 'Je', 'jr': 'Je',
    'lamentations': 'La', 'lam': 'La', 'la': 'La',
    'ezekiel': 'Eze', 'ezek': 'Eze', 'eze': 'Eze', 'ez': 'Eze',
    'daniel': 'Da', 'dan': 'Da', 'da': 'Da', 'dn': 'Da',
    'hosea': 'Ho', 'hos': 'Ho', 'ho': 'Ho',
    'joel': 'Joe', 'joe': 'Joe', 'jl': 'Joe',
    'amos': 'Am', 'am': 'Am',
    'obadiah': 'Ob', 'obad': 'Ob', 'ob': 'Ob',
    'jonah': 'Jon', 'jnh': 'Jon',
    'micah': 'Mic', 'mic': 'Mic', 'mi': 'Mic',
    'nahum': 'Na', 'nah': 'Na', 'na': 'Na',
    'habakkuk': 'Hab', 'hab': 'Hab', 'hb': 'Hab',
    'zephaniah': 'Zep', 'zeph': 'Zep', 'zep': 'Zep',
    'haggai': 'Hag', 'hag': 'Hag', 'hg': 'Hag',
    'zechariah': 'Zec', 'zech': 'Zec', 'zec': 'Zec',
    'malachi': 'Mal', 'mal': 'Mal',
    // New Testament
    'matthew': 'Mt', 'matt': 'Mt', 'mt': 'Mt',
    'mark': 'Mk', 'mk': 'Mk', 'mr': 'Mk',
    'luke': 'Lk', 'lk': 'Lk', 'lu': 'Lk',
    'john': 'Jn', 'jn': 'Jn', 'jhn': 'Jn',
    'acts': 'Ac', 'ac': 'Ac',
    'romans': 'Ro', 'rom': 'Ro', 'ro': 'Ro', 'rm': 'Ro',
    '1corinthians': '1Co', '1cor': '1Co', '1co': '1Co', 'icorinthians': '1Co', 'icor': '1Co',
    '2corinthians': '2Co', '2cor': '2Co', '2co': '2Co', 'iicorinthians': '2Co', 'iicor': '2Co',
    'galatians': 'Ga', 'gal': 'Ga', 'ga': 'Ga',
    'ephesians': 'Eph', 'eph': 'Eph',
    'philippians': 'Php', 'phil': 'Php', 'php': 'Php',
    'colossians': 'Col', 'col': 'Col',
    '1thessalonians': '1Th', '1thess': '1Th', '1th': '1Th', 'ithessalonians': '1Th', 'ithess': '1Th',
    '2thessalonians': '2Th', '2thess': '2Th', '2th': '2Th', 'iithessalonians': '2Th', 'iithess': '2Th',
    '1timothy': '1Ti', '1tim': '1Ti', '1ti': '1Ti', 'itimothy': '1Ti', 'itim': '1Ti',
    '2timothy': '2Ti', '2tim': '2Ti', '2ti': '2Ti', 'iitimothy': '2Ti', 'iitim': '2Ti',
    'titus': 'Tt', 'tit': 'Tt', 'tt': 'Tt',
    'philemon': 'Phm', 'phlm': 'Phm', 'phm': 'Phm',
    'hebrews': 'Heb', 'heb': 'Heb',
    'james': 'Jas', 'jas': 'Jas', 'jm': 'Jas',
    '1peter': '1Pe', '1pet': '1Pe', '1pe': '1Pe', '1pt': '1Pe', 'ipeter': '1Pe', 'ipet': '1Pe',
    '2peter': '2Pe', '2pet': '2Pe', '2pe': '2Pe', '2pt': '2Pe', 'iipeter': '2Pe', 'iipet': '2Pe',
    '1john': '1Jn', '1jn': '1Jn', 'ijohn': '1Jn', 'ijn': '1Jn',
    '2john': '2Jn', '2jn': '2Jn', 'iijohn': '2Jn', 'iijn': '2Jn',
    '3john': '3Jn', '3jn': '3Jn', 'iiijohn': '3Jn', 'iiijn': '3Jn',
    'jude': 'Jud', 'jud': 'Jud',
    'revelation': 'Re', 'rev': 'Re', 're': 'Re', 'apocalypse': 'Re', 'apoc': 'Re',
};

/**
 * Maps translation display names to Logos ref.ly codes
 */
export const VERSION_MAPPING: Record<string, string> = {
    'esv': 'esv',
    'nasb': 'nasb95',
    'niv': 'niv2011',
    'lsb': 'lgcystndrdbblsb',
    'nlt': 'nlt'
};
